### PR TITLE
restore PWM coefficient to 5000 because 2000 produces unrealistic res…

### PR DESCRIPTION
**Pull request by drleavsy**
Please refer to this forum : https://electronics.stackexchange.com/questions/262473/mh-z19-co2-sensor-giving-diferent-values-using-uart-and-pwm

### CODE REVIEW

**Comment by tobiasschuerg** [comment]
@drleavsy thanks for contributing!
I think, just changing it (back) to 5000 does not fix the general issue.

As  pointed out in #27 the range will not be the same for everyone.
To address this issue the range (2000 or 5000) should be configurable - ideally it is initially read from the sensor (command `0x99`) and then used...

**Review by tobiasschuerg — CHANGES_REQUESTED** [review]
@drleavsy thanks for contributing!
I think, just changing it (back) to 5000 does not fix the general issue.

As  pointed out in #27 the range will not be the same for everyone.
To address this issue the range (2000 or 5000) should be configurable - ideally it is initially read from the sensor (command `0x99`) and then used...

**Comment by drleavsy** [comment]
> @drleavsy thanks for contributing! I think, just changing it (back) to 5000 does not fix the general issue.
> 
> As pointed out in #27 the range will not be the same for everyone. To address this issue the range (2000 or 5000) should be configurable - ideally it is initially read from the sensor (command `0x99`) and then used...

If I understood correctly from the manual, we can set the range with command `0x99` , but we cannot read it from the device. So the user can set 2000 or 5000 range "manually" from their own Arduino code, but we cannot detect it "automatically" from the MHZ library with the command `0x99`. So I suggest to leave  the range selection to the user, but give him/her the capability to set the range in the class constructor.

**Comment by drleavsy** [comment]
Accidently closed it

**Pull request closed without merging**
